[build]
  command = "NODE_OPTIONS=--max-old-space-size=3072 RSPRESS_SSG_WORKER_THREAD_COUNT=1 npx rspress build"
  publish = "doc_build"

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "https://www.unpkg.com"

[[redirects]]
  from = "/next/*"
  to = "/:splat"
  status = 200